spring.application.name: gateway

info.app.name: ${spring.application.name}

server.port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka